name: Manual Docs Build
on:
  workflow_dispatch:
    inputs:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Launching build script
      run: npm i && chmod 777 site/deploy.sh && ./site/deploy.sh
